---
bibliography: ../biblio.bib
output: pdf_document

---


# Missing Data --- Imputation etc

# Notes from 2015-10-03

- Netflix Challenge --> becomes "fashion"
- aka "Matrix completion"

## Literature

### Books and Papers

- [Schafer & Graham](http://www.nyu.edu/classes/shrout/G89-2247/Schafer&Graham2002.pdf)
  Missing Data: Our View of the State of the Art, American Psychological
  Association. [@schafer2002missing]

- [@little2002statistical] Roderick J.A. Little and Donald B. Rubin
  Statistical Analysis with Missing Data  (Wiley; 2nd ed., 2002)
  Freely available (chapter wise) via [ETH Library](http://www.library.ethz.ch/primo_library/libweb/action/search.do?cs=frb&ct=frb&frbg=123779766&fctN=facet_frbrgroupid&fctV=123779766&doc=ebi01_prod010259824&lastPag=&lastPagIndx=1&rfnGrp=frbr&frbrSrt=date&dscnt=0&vl%28611274651UI1%29=all_items&vl%28134576197UI0%29=any&frbg=&scp.scps=scope%3A%28ELENDING%29%2Cscope%3A%28%22ARCHIVDATENBANK%22%29%2Cscope%3A%28data_archive%29%2Cscope%3A%28ebi01_prod%29%2Cscope%3A%28EPICS%29%2Cscope%3A%28replay%29%2Cscope%3A%28retroseals%29%2Cscope%3A%28cmistar%29&tab=default_tab&dstmp=1442558558993&srt=rank&ct=search&mode=Basic&&dum=true&indx=1&tb=t&vl%281UIStartWith0%29=contains&vl%28freeText0%29=Little%20Rubin%20%22missing%20data%22&vid=DADS&fn=search)

- [Joseph L. Schafer](http://sites.stat.psu.edu/~jls/) seminal monograph
  Schafer, J.L. (1997) Analysis of Incomplete Multivariate Data, Chapman &
  Hall, London. [@schafer1997analysis]

  
 Came with 4 S-PLUS "packages" called  NORM, CAT, MIX, PAN}
 --> http://sites.stat.psu.edu/~jls/misoftwa.html

 Versions of all four of these are available on CRAN:
```{r}
sapply(c("norm", "cat", "mix", "pan"), packageDescription)
```

## R packages

### Bioconductor:
#### impute : Hastie et al:  knn.impute()
Based on [missing.pdf](file:///u/maechler/save/papers/Hastie-etc/imputing-missing_1999.pdf)
paper, Hastie et al. (1999).

### CRAN

#### [CRAN task view 'Multivariate'](https://cran.ch.r-project.org/web/views/Multivariate.html)
  has section __Missing data__  (which seems *not* comprehensive to me):

	[mitools] provides tools for multiple imputation,
	[mice] provides multivariate imputation by chained equations
	[mvnmle] provides ML estimation for multivariate normal data with missing values,
	[mix] provides multiple imputation for mixed categorical and continuous data.
	[pan] provides multiple imputation for missing panel data.
	[VIM] provides methods for the visualisation as well as imputation of missing data.
	aregImpute() and transcan() from [Hmisc] provide further imputation methods.
	[monomvn] deals with estimation models where the missing data pattern is monotone.

#### Schafer's  ("norm", "cat", "mix", "pan") -- see above

#### Lumley's ['mitools'](https://cran.ch.r-project.org/web/package=mitools)


#### imputeR

#### softImpute:
	Title: Matrix Completion via Iterative Soft-Thresholded SVD
	Version: 1.4
	Date: 2015-2-13
	Author: Trevor Hastie and Rahul Mazumder



#### imputation : Archived in 2014 (policy violation: running on all cores)
- by Jeff Wong  [on Github](https://github.com/jeffwong/imputation)
- also mentions the important paper by Cai, Candes, Shen et al
	 [(preprint on ArXiv)](http://arxiv.org/format/0810.3286v1),
	 _Singular Value Thresholding Algorithm for Matrix Completion_

### (We)blogs etc on R packages:

#### Amelia

#### Mad (Data) Scientist

## Notes from 2015-10-15 meeting

- Focus on either continuous or mixed case
- Find data sets that are historically relevant:
    * See in the packages if there is a common package
    * Use the data sets in the appendix of [@schafer1997analysis], FLAS inside
      the `miP`
      [package](http://finzi.psych.upenn.edu/library/miP/html/FLAS.html).
    * Use the synthetic bivariate set of [@schafer2002missing], (normal and
      cluster).
    * Data sets: titanic, iris, mtcars, yeast [@lichman2013yeast], (noisy) time
      series data?      
- Concentrate on the modern methods for next meeting [@troyanskaya2001missing]
  and [@hastie1999imputing].
- Keep up with reading.
- Notation should be consistent, if possible with either [@schafer1997analysis]
  or [@little2002statistical].
- Next meeting 2015-11-02 at 3pm.

## Note from 2015-11-02 meeting


- [vim package](https://cran.r-project.org/src/contrib/Archive/miP/). See
  article. It allows to display the pattern of missingness.
- Start playing with mice, mix and pan packages.
- KNN: The weights in KNN are usually $w(d) = 1/d$, however nothing prevent us
  of having $w(d) = K(d)$ where $K$ is any valid Kernel.
- Euclidian distance:
    + On which observations do we perform the comparison?
    + What type of standardization?
- MCAR, MAR and MNAR are an univariate properties: columns in a data matrix
  might have different assumptions on their missingness mechanism.
- 2014: Find paper on Weighted KNN ofr missing data.
- MICE used chained equations, AMELIA is clearly bayesian.
- Health and NHANES data sets are used widely.
- Use 20 imputation for the FLAS data sets to complete the missing variables
  and use it as the reference data set.
- Next meeting 2015-11-16 at 11am.

## Note from 2015-11-02

- Using the FLAS data set, we should average the imputation with several
  packages.
- Use data frequency of the missing pattern to create artificial missingness.
- MCAR as well.
- Next meeting 2015-11-23 at 11am.

## Note from 2015-11-30

- MAR fashion set the percentage of missingness by counting the number of NA
  data.
- Use $(\hat x_{ij} - x_{ij})/x_{\dot j}$ to compute the MSE and the 0-1 loss
  for category.
- SoftImpute, impute and try to set tuning for mi, Amelia.
- 20 imputes and pool for imputations methods.

# Bibliography

[//]: Definitions of References --- all this is **not** visible on final doc!

[mitools]: https://cran.ch.r-project.org/package=mitools
[mice]: https://cran.ch.r-project.org/package=mice
[mvnlme]: https://cran.ch.r-project.org/package=mvnlme
[mix]: https://cran.ch.r-project.org/package=mix
[pan]: https://cran.ch.r-project.org/package=pan
[VIM]: https://cran.ch.r-project.org/package=VIM
[Hmisc]: https://cran.ch.r-project.org/package=Hmisc
[monomvn]: https://cran.ch.r-project.org/package=monomvn

