all: full partial

full:
	echo "Making plot for full dataset"
	R CMD BATCH output_analysis_fulldataset.R &

partial:
	echo "Making plot for partial dataset"
	R CMD BATCH output_analysis_partialdataset.R &
